import re
import sqlite3

import requests

OLLAMA_URL = "http://localhost:11434/api/generate"


def initialize_sample_db(conn):
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS customers (
            customer_id INTEGER PRIMARY KEY,
            customer_name TEXT NOT NULL
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS orders (
            order_id INTEGER PRIMARY KEY,
            customer_id INTEGER NOT NULL,
            order_total REAL NOT NULL,
            FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
        )
        """
    )

    if conn.execute("SELECT COUNT(*) FROM customers").fetchone()[0] == 0:
        conn.executemany(
            "INSERT INTO customers (customer_id, customer_name) VALUES (?, ?)",
            [
                (1, "Alice"),
                (2, "Bob"),
                (3, "Charlie"),
                (4, "Dana"),
                (5, "Evan"),
            ],
        )

    if conn.execute("SELECT COUNT(*) FROM orders").fetchone()[0] == 0:
        conn.executemany(
            "INSERT INTO orders (order_id, customer_id, order_total) VALUES (?, ?, ?)",
            [
                (101, 1, 120.0),
                (102, 1, 89.5),
                (103, 2, 210.0),
                (104, 2, 145.0),
                (105, 3, 300.0),
                (106, 3, 75.0),
                (107, 4, 500.0),
                (108, 5, 180.0),
                (109, 5, 220.0),
                (110, 5, 90.0),
            ],
        )

    conn.commit()


def get_schema(conn):
    tables = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
    ).fetchall()
    schema = []
    for (table_name,) in tables:
        cols = conn.execute(f"PRAGMA table_info({table_name})").fetchall()
        schema.append(f"Table: {table_name}")
        for col in cols:
            schema.append(f"  - {col[1]} ({col[2]})")
    return "\n".join(schema)


def sanitize_sql(raw_sql: str) -> str:
    sql = raw_sql.strip()
    sql = re.sub(r"^```sql\s*", "", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\s*```$", "", sql, flags=re.IGNORECASE)
    sql = sql.strip()
    if not sql:
        raise ValueError("No SQL generated by the model.")
    return sql


def generate_sql(question, schema):
    prompt = f"""
You are a SQL expert.
Use the following schema:
{schema}

Return only SQL.
Question: {question}
"""
    payload = {
        "model": "qwen2.5-coder:7b",
        "prompt": prompt,
        "stream": False,
        "options": {"temperature": 0.1},
    }
    r = requests.post(OLLAMA_URL, json=payload, timeout=120)
    r.raise_for_status()
    return sanitize_sql(r.json()["response"])


conn = sqlite3.connect("sample.db")
initialize_sample_db(conn)
schema = get_schema(conn)
question = "What are the top 5 customers by total order value?"
sql = generate_sql(question, schema)
print("Generated SQL:")
print(sql)

if "DROP" not in sql.upper() and "DELETE" not in sql.upper():
    rows = conn.execute(sql).fetchall()
    print(rows)

conn.close()